export { default as Home } from './home/Home';
export { default as Cart } from './cart/Cart';
export { default as Shipping } from './shipping/Shipping';
export { default as Payment } from './payment/Payment';
export { default as Summary } from './summary/Summary';
export { default as Confirm } from './confirmation/Confirm';
export { default as NotFound } from './404/NotFound';
export { default as Login } from './authentication/Login';
export { default as Register } from './authentication/Register';